<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\MstEmployees */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Mst Employees', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-content">
    <div class="page-header">
        <h1>
            <?= Html::encode($this->title) ?>
        </h1>
    </div>
    <div class="mst-employees-view">

        <p>
            <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary btn-sm']) ?>
            <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger btn-sm',
                'data' => [
                    'confirm' => 'Are you sure you want to delete this item?',
                    'method' => 'post',
                ],
            ]) ?>
        </p>

        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
            'mst_institution_id',
            'mst_department_id',
            'mst_designation_id',
            'salutation',
            'emp_fname',
            'emp_mname',
            'emp_lname',
            'emp_type',
            'emp_guardtype',
            'emp_guardname',
            'emp_maritalstatus',
            'emp_dob',
            'emp_age',
            'emp_gender',
            'emp_nationality',
            'emp_qual',
            'emp_jdate',
            'emp_rdate',
            'remarks:ntext',
            'emp_omail',
            'emp_pmail',
            'emp_handphone',
            'emp_landphone',
            'emp_paddress:ntext',
            'emp_pcountry_id',
            'emp_pstate_id',
            'emp_pcity_id',
            'emp_caddress:ntext',
            'emp_ccountry_id',
            'emp_cstate_id',
            'emp_ccity_id',
            'emp_photo',
            'status',
            'is_deleted',
            'created_date',
            'created_by',
            'modified_date',
            'modified_by',
            'emp_ext_no',
            'user_name',
            'password',
            'emp_guardian_name',
            'emp_mother_name',
            'mst_community_id',
            'mst_caste_id',
            'fax',
            'pan',
            'emp_is_physically_challanged',
            'miniority_indicator',
            'emp_is_ft_pt',
            'appointment_type',
            'faculty_type',
            'mst_course_id',
            'emp_pay_scale_type',
            'emp_salary_mode',
            'emp_bank_acc_no',
            'emp_bank_branch_name',
            'emp_bank_ifsc_code',
            'emp_esi_no',
            'emp_pf_no',
            'teaching_experience',
            'total_work_experience',
            'research_experience',
            'no_national_publications',
            'no_of_patents',
            'no_of_pg_projects_guided',
            'no_of_doctorate_students_guided',
            'no_of_international_publications',
            'no_of_books_published',
            'is_first_yr_teacher',
            'is_fy_common_subject_teacher',
            'fy_common_subject_name',
            'is_aicte_work_member',
            'is_aicte_grants_assistance',
            'is_approve_new',
            'is_approve_modified',
            'nominee_name',
            'nominee_relation',
            'emp_bank_name',
            'emp_handphone_1',
            'mst_blood_group_id',
            'emp_basic_pay',
            'emp_gross_pay',
            'emp_hra',
            'emp_other_allowance',
            'emp_da_percentage',
            'emp_bio_metric_id1',
            'emp_bio_metric_id2',
            'emp_religion',
            'emp_ars_track',
            'profile_edit_flag',
            'approve_message_flag',
            'emp_is_phychallanged',
            'employee_status',
            'resigned_date',
            'resigned_reason:ntext',
            'suspended_from_date',
            'suspended_to_date',
            'suspended_reason:ntext',
            'spouse_name',
            'father_name',
            'scan_signature',
            'state_of_origin',
            'caddress_1',
            'caddress_2',
            'caddress_3',
            'paddress_1',
            'paddress_2',
            'paddress_3',
            'scale_of_pay',
            'next_increment_date',
            'substitute_faculty_id',
            'fip_start_date',
            'fip_end_date',
            'nature_of_handicap',
            'emp_physically_challanged_desc:ntext',
            'emp_spouse_name',
            'emp_com_paddress:ntext',
            'emp_com_caddress:ntext',
            'emp_fullname',
            'area_of_specialization',
            'mst_programme_id',
            'seniority_order',
            'is_emp_qualified',
            'emp_qualified_type',
            'emp_qualification_approval_no',
            'emp_qualification_approval_date',
            'emp_qualification_temp_approval_no',
            'emp_qualification_temp_approval_date',
            'emp_qualification_temp_approval_exp_date',
            'emp_omail_domain',
            'empno',
            'emp_sname',
            'emp_pzipcode',
            'emp_czipcode',
            'adhar_no',
            ],
        ]) ?>

    </div>
</div>